name: Non main pushes and PRs

on:
  push:
    branches-ignore:
      - main

jobs:
  check:
    name: Check code style
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: "3.7"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry==1.1.13
        poetry config virtualenvs.create false --local
        poetry install

    - name: Run black
      run:  black . --check

    - name: Run isort
      run:  isort . --check-only